# This is a generated file. Not intended for manual editing.
services:
  tennis:
    build:
      context: "/Users/janstrnad/repos/Tennis"
      dockerfile: "Tennis.App/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "tennis:dev"
    ports:
    - "127.0.0.1:57002:57100"
    - "127.0.0.1:57202:57300"
    volumes:
    - "/Users/janstrnad/.nuget/packages:/root/.nuget/packages"
    - "/Users/janstrnad/repos/Tennis/Tennis.App:/app:rw"
    - "/Users/janstrnad/repos/Tennis:/src:rw"
    - "/Users/janstrnad/.local/share/JetBrains/RiderRemoteDebugger/2023.3.4/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/janstrnad/Library/Logs/JetBrains/Rider2023.3/DebuggerWorker/JetBrains.Debugger.Worker.2024_4_01_16_56_41:/var/opt/rider-debugger:rw"
    working_dir: "/app"
